# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-10 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('color', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '鞋子',
                'verbose_name_plural': '鞋子',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '姓名',
                'verbose_name_plural': '姓名',
            },
        ),
        migrations.AddField(
            model_name='shoes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.User'),
        ),
    ]
